source 'https://github.com/CocoaPods/Specs.git'
target 'MultipleLocationRoutes' do
platform :ios, '10.0'

use_frameworks!

pod 'GoogleMaps'
pod 'GooglePlaces'

pod 'Alamofire', '~> 4.2.0'
pod 'SwiftyJSON'

end

